### PR TITLE
fix(labeling): add plugin label for resources managed via k8s plugin

### LINKED ISSUE #42: The plugin should add annotation to the resources it creates
The plugin should annotate resources it creates prior to applying them to the cluster.

something like: `"plugin.spinnaker.io": "aws.ManagedDeliveryK8sPlugin"`

/cc @nabuskey

### PR DESCRIPTION
**Pull request by nimakaviani**
this in combination with the application name that is added to all spinnaker
resources allows users to filter out k8s resources created through  managed delivery.

fixes #42

### CODE REVIEW

**Comment by nimakaviani** [comment]
@nabuskey just a heads up that merging this will probably give you some conflicts in your other line of work.

File: k8s-plugin/src/main/kotlin/com/amazon/spinnaker/keel/k8s/K8sConfig.kt [hunk 1]
```diff
@@ -15,7 +15,9 @@ const val K8S_PROVIDER = "kubernetes"
 const val SOURCE_TYPE = "text"
 
 const val K8S_LAST_APPLIED_CONFIG: String = "kubectl.kubernetes.io/last-applied-configuration"
-const val KEEL_MONIKER_APP: String = "moniker.spinnaker.io/application"
+const val KEEL_MONIKER_APP_ANNOTATION: String = "moniker.spinnaker.io/application"
```
Comment (nabuskey) [inline k8s-plugin/src/main/kotlin/com/amazon/spinnaker/keel/k8s/K8sConfig.kt:18]: This doesn't seem to be used. What is this for?

File: k8s-plugin/src/main/kotlin/com/amazon/spinnaker/keel/k8s/K8sConfig.kt [hunk 2]
```diff
@@ -15,7 +15,9 @@ const val K8S_PROVIDER = "kubernetes"
...
+const val MANAGED_DELIVERY_APP_LABEL = "md.spinnaker.io/plugin"
+const val MANAGED_DELIVERY_K8S_PLUGIN = "k8s"
```
Comment (nabuskey) [inline k8s-plugin/src/main/kotlin/com/amazon/spinnaker/keel/k8s/K8sConfig.kt:20]: Wonder if we should create a list of label pairs to apply instead since they are tightly coupled. We may need to add more labels in the future as well?
 `val MANAGED_DELIVERY_APP_LABEL = listOf(Pair("md.spinnaker.io/plugin", "k8s"))`

**Review by nabuskey — APPROVED** [review]
LGTM just a question and a label definition suggestion.

File: k8s-plugin/src/main/kotlin/com/amazon/spinnaker/keel/k8s/K8sConfig.kt (hunk 1 above)
Comment (nimakaviani) [reply k8s-plugin/src/main/kotlin/com/amazon/spinnaker/keel/k8s/K8sConfig.kt:18]: yeah I dont think we use it. I can remove it.

File: k8s-plugin/src/main/kotlin/com/amazon/spinnaker/keel/k8s/K8sConfig.kt (hunk 2 above)
Comment (nimakaviani) [reply k8s-plugin/src/main/kotlin/com/amazon/spinnaker/keel/k8s/K8sConfig.kt:20]: yeah good idea! will fix.
